### ISSUE TITLE
Request to have access to all records/rows for a recordhook

### ISSUE THREAD

**Issue by duchess-toffee** [FlatFilers/Adapter#116]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
**Request**: To be able to have access to all the records/rows for a record hook, similar to how the submit functionality provides the user with `FlatfileResults`.
**Issue**: Currently the record hooks on init will send a request per record for validation. This is pretty ineffective and bogs down the server with requests (especially when there's a bigger data set to validate for). I know Flatfile offers field hooks as well, but field hooks cannot be used to validate against other fields within a row. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
* 
I see that Flatfile automatically sets `bulkInit` to true and then runs the `bulkHookCallback`. Is there a leverage similar structure/functionality and optionally use a custom callback instead when provided by the user?

**Comment by brentkulwicki** [comment]
Thank you for the feature request. We have passed this request on to our product team. 

One note: We have had people in the past who have used fieldHooks and set the values of a field hook to a variable to then reference within other field hooks or even reference hooks. The only catch with this is that you would have to reference in the index value on each of the fields you are wanting to compare. You can even do field hooks and stitch them together this way on the backend of your application and send the responses for the field hooks back once you've used them all. 

Feel free to reach out to our support team at flatfile.com if you need help with any of this.

**Comment by chawes13** [comment]
@brentkulwicki Any thoughts on how to keep this variable up-to-date when the user deletes a row? It looks like record hooks fire on init and change, but not delete. Is there a global lifecycle event I could subscribe to?

**Comment by brentkulwicki** [comment]
There is not currently a delete method for this. This will be something that will be touched on in our current v3 product, but likely will not be developed for v2 of the product which is what this original post is referring to.
