### ISSUE TITLE
Keys are being used for messages to the user when labels should be. 

### ISSUE THREAD

**Issue by lramirez925** [FlatFilers/Adapter#31]
* **I'm submitting a ...**
[ X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
When a user uploads a file which does not have required columns in it. The alert that the user gets returns the keys for any missing required columns instead of the labels. This makes it extremely confusing for a user when keys are not exactly the same as the column names. 

All alerts to the user should return the label for the column. This also occurs for mismatched select options when the label and value keys are used. 

![Screen Shot 2019-12-20 at 3 21 30 PM](https://user-images.githubusercontent.com/15653933/71290052-d5c9bf00-233c-11ea-9c59-f8ba33511898.png)

* **Other information**
To recreate use the vanilla Jquery example, make multiple columns required. Upload a csv with only a robot name column. Try to continue past the mapping section. You will see a similar message to what I have in the screen shot. 

Feel free to contact me about this problem, I have reported multiple issues to sales folks who have contacted me but have heard nothing about any of the issues. So I have started reporting here. If this is not the correct place to report issues please give me a contact or location where I can report them. This is a show stopper currently for us to use in production code as our keys are not always user friendly.

**Comment by dboskovic** [comment]
Thanks for reporting this. We're actively working on an update to this experience and will follow up once it's available. We should be able to get you preview access this week.

**Comment by mrpbrain** [comment]
@lramirez925 This issue has definitely been resolved in v2 of the importer. If you haven't already, please try it out!
