### ISSUE TITLE
Row meta data needed for more complex validation 

### ISSUE THREAD

**Issue by kchaplick** [FlatFilers/Adapter#34]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
When validation is done through the importer by manually entering data into the cells, each record that is sent through has metadata, including the row number. This row number can be used to create functions that allow interrow validation (such as all items with the same sku number have the same price) and errors to be passed to the FlatFile validator. When uploading a file there is no metadata (so no row number) so you cannot pass it to the validator. The workaround is to use requestCorrectionsFromUsers which isn't ideal because it doesn't tell the user which cells are invalid. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by dboskovic** [comment]
Hey @kchaplick - we have a beta we can enroll you in which allows you to use a new function in the SDK called "registerDataHook" which provides row number to the validator callback (and) lets you mutate / normalize the data too! Can you reach out to Flatfile support chat with your account info to get on this list?

**Comment by kchaplick** [comment]
Awesome, thanks!
