### ISSUE TITLE
Error when using registerFieldHook()

### ISSUE THREAD

**Issue by OneParishLukas** [FlatFilers/Adapter#40]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Here is the error I am receiving when trying to use the registerFieldHook:

`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

This is my code:

```
importer.registerFieldHook("phone", (values) => {
                console.log('these are values');
                console.log(values);
                return [
                    [
                        {
                            value: values[0][0].replace(/^(\d{3})(\d{3})(\d{4})+$/, "($1) $2-$3"),
                            info: [
                                {
                                    message: "Phone numbers were formatted.",
                                    level: "info"
                                }
                            ]
                        },
                        values[0][1]
                    ]
                ];
            });

```

**Comment by OneParishLukas** [comment]
Oh yeah, this is the code that is triggering the error:
[listenersToRegister.push([window, 'wheel', function (event) {
          var overlay = void 0;
          var deltaY = event.wheelDeltaY || event.deltaY;
          var deltaX = event.wheelDeltaX || event.deltaX;

          if (_this.topOverlay.clone.wtTable.holder.contains(event.realTarget)) {
            overlay = 'top';
          } else if (_this.bottomOverlay.clone && _this.bottomOverlay.clone.wtTable.holder.contains(event.realTarget)) {
            overlay = 'bottom';
          } else if (_this.leftOverlay.clone.wtTable.holder.contains(event.realTarget)) {
            overlay = 'left';
          } else if (_this.topLeftCornerOverlay && _this.topLeftCornerOverlay.clone && _this.topLeftCornerOverlay.clone.wtTable.holder.contains(event.realTarget)) {
            overlay = 'topLeft';
          } else if (_this.bottomLeftCornerOverlay && _this.bottomLeftCornerOverlay.clone && _this.bottomLeftCornerOverlay.clone.wtTable.holder.contains(event.realTarget)) {
            overlay = 'bottomLeft';
          }

          if (overlay == 'top' && deltaY !== 0 || overlay == 'left' && deltaX !== 0 || overlay == 'bottom' && deltaY !== 0 || (overlay === 'topLeft' || overlay === 'bottomLeft') && (deltaY !== 0 || deltaX !== 0)) {

            event.preventDefault();
          }
        }]);
      }](url)

Specifically, this line: handsontable.js:22082
`event.preventDefault()`

**Comment by mrpbrain** [comment]
@OneParishLukas This issue appears to be resolved now, in v2 of the importer.
If you haven't already, please give it a try and please let us know if you run into any more issues!
