### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by harlyon** [FlatFilers/Adapter#43]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
after uploading a CSV, when it gets to the match column, the toggle switch isn't working.
![Screen Shot 2020-04-14 at 10 49 34](https://user-images.githubusercontent.com/29041253/79205291-024e9d00-7e3e-11ea-8090-17c08ea1de90.png)
is there a way to make this toggle work accordingly

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by mrpbrain** [comment]
@harlyon Hi there! It looks like your screenshot is from v1, which is now deprecated.
This issue should **definitely** be resolved in our new v2 importer. If you haven't already, please give that a try!
