### ISSUE TITLE
Nested objects

### ISSUE THREAD

**Issue by rajank-px** [FlatFilers/Adapter#46]
* **I'm submitting a ...**
[x] bug report
[x] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**
Below is my CSV:
`'name.first,name.last,job\n', 'foo,bar,teacher\n'`
After CSV parse it is generating a flat object instead of a nested object. I am expecting below format
`{
   name: {
                 first: 'foo',
                 last: 'bar'
              },
   job: 'teacher'
}`

I could not find any document related to nested objects hence requesting here for more info.

* **Other information / Bug** 
Also one thing I have noticed - If header value is separated with dot(for example name.first) and if I try to inline edit the related cell values then it is clearing the cell values and I have to enter fresh data into it. (Note: Inline edit works perfectly fine if header value is something like 'job').

**Comment by mrpbrain** [comment]
To get nested objects using the dot notation, please include the **unflatten** library in your project (https://www.npmjs.com/package/unflatten)!

Regarding the headers with dot notations, that you for pointing that out! I'll check that out and work on getting it resolved, if it's still happening.

**Comment by brentkulwicki** [comment]
Thanks for your feature request. Our product team has put this on our roadmap for a future product update. Closing this issue as we track these features elsewhere.
