### ISSUE TITLE
nextChunk() 

### ISSUE THREAD

**Issue by TuffDev** [FlatFilers/Adapter#48]
* **I'm submitting a ...**
[ x ] bug report

* **Summary**
Using version 0.2.9
I'm having an issue with the chunking functionality.  I'm setting the {inChunks: 200} in the requestDataFromUser and I'm getting an error:
`Uncaught (in promise) "nextChunk()" is only accessible when using "inChunks". Please see docs for "requestDataFromUser".`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I've tried the version used in [this codesandbox](https://codesandbox.io/s/vanilla-flatfile-wstreaming-5n6hs?file=/src/index.js) and got the same error.  I copied the code from this sandbox almost verbatim.

**Comment by wouter-toppy** [comment]
Same issue here. looks likes when you get the results. `inChunks` not getting set in `$meta`

**Comment by wouter-toppy** [comment]
as it turns out, ist not working with `FlatfileImporter.setVersion(2);` if you leave it in Version 1 its working without problem

**Comment by macoybarayan** [comment]
Is there any fix of this? I get same error.

**Comment by macoybarayan** [comment]
I hope this one is fixed on version 2 so I dont need to switch version 1.

**Comment by wouter-toppy** [comment]
Ive contacted the support a few weeks ago. they said in V2 there is no need to use chunks again. even though i not completely agreed with that. because we importing a lot of data we want to process. I splitted up the data in chunks myself.

```js
                    $("#flatfile-import").click(function() {
                        importer
                            .requestDataFromUser()
                            .then(function(result) {
                                var data = result.data,
                                    currentChunk = 0,
                                    perc = 0,
                                    totalChunks = Math.ceil(data.length / 500);

                                function handleChunk(chunk) {
                                    currentChunk++;

                                    //YOUR CODE (Ajax in example)
                                    $.ajax({
                                        url: 'url',
                                        method: 'POST',
                                        dataType: 'json',
                                        contentType: 'application/json',
                                        data: JSON.stringify({
                                            chunkData: chunk,
                                            currentChunk: currentChunk,
                                            totalChunks: totalChunks
                                        })
                                    }).always(function (){
                                        perc = Math.ceil(100 * (currentChunk / totalChunks));
                                        importer.displayLoader(`${perc}% [${currentChunk}/${totalChunks}] (${chunk.length} rows) imported...`);

                                        if (totalChunks > currentChunk) {
                                            handleChunk(data.splice(0,500));
                                        } else {
                                            importer.displaySuccess("Import successful!");
                                        }
                                    });
                                }

                                importer.displayLoader(`Starting import...`);

                                handleChunk(data.splice(0,500));
                            })
                            .catch(function(error) {
                                console.log(error);
                            });
                    });
```

**Comment by macoybarayan** [comment]
Thanks @wouter-toppy .. it works like a charm. I hope they update their API documentation as some is not working.

**Comment by mrpbrain** [comment]
@macoybarayan Hi there! We did just publish updated documentation about 2 weeks ago, at https://developers.flatfile.io

We are updating it more actively now, including removing references to the deprecated inChunks and nextChunk().
If you run into anything else that isn't working as described, please let us know and we'll fix it right away!

**Comment by mrpbrain** [comment]
Closing this issue because, as @wouter-toppy shared above, chunks has been deprecated from Flatfile in v2.
However, @wouter-toppy's example is great if you need to split data!

**Comment by hdsheena** [comment]
What are we supposed to use to split the data now? There is no inbuilt solution anymore?

**Comment by wouter-toppy** [comment]
@hdsheena like i mentioned above. you can split it up by yourself.
