### ISSUE TITLE
"All values pass validation for this field" when none do

### ISSUE THREAD

**Issue by jdsaund** [FlatFilers/Adapter#50]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Mapping a column that is configured to match a regex passes validation when every value in the column should fail:
![image](https://user-images.githubusercontent.com/4198362/85500474-eda13900-b626-11ea-83b7-6709d5f61f9f.png)

The `fields` config:
```
[
  {
    label: 'delivery date',
    key: 'deliveryDate',
    validators: [
      { validate: 'regex_matches', regex: '^\\d{2}[\\s-/]\\d{2}[\\s-/]\\d{4}$' }
    ]
  }
]
```

When proceeding to the Review step, the validation then fails as expected:
![image](https://user-images.githubusercontent.com/4198362/85500519-027dcc80-b627-11ea-8d46-94e9e2354eaa.png)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by dboskovic** [comment]
This is definitely an issue! Thanks for reporting.

**Comment by MaksymBlank** [comment]
Fixed and merged.
