### ISSUE TITLE
I can't input anything manually or select the right column

### ISSUE THREAD

**Issue by fuchien** [FlatFilers/Adapter#54]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[X] question about how to use this project

* **Summary**
![image](https://user-images.githubusercontent.com/15007654/87795336-47f47a80-c81e-11ea-90c9-cb3007592d07.png)
I **follow** [codesandbox](https://codesandbox.io/s/1896q2v4zl?from-embed=&file=/src/index.js) config and lib version. (0.2.9 and 0.2.12)
![image](https://user-images.githubusercontent.com/15007654/87795564-a28dd680-c81e-11ea-9668-0ce470ad7c16.png)

But not working to input manually, or just select the right column name.
I tried to input, but nothing happen or just click in select, but will close immediate.
![image](https://user-images.githubusercontent.com/15007654/87795480-7bcfa000-c81e-11ea-96ae-d16b25d67a6c.png)

I don't know if is problem with my config or browser, but I also tested in Safari and Chrome.

And this url https://developers.flatfile.io/docs/react/fields can't open. 404.

Another thing is about initialize with data.
![image](https://user-images.githubusercontent.com/15007654/88100335-c7fa4780-cb72-11ea-92b5-6452e554e2cf.png)
I follow steps in codesandbox.
But is not working.
![image](https://user-images.githubusercontent.com/15007654/88100591-1c052c00-cb73-11ea-8d34-428d9cd6ee6f.png)
https://codesandbox.io/s/flatfile-react-eopt0?file=/src/index.js

Someone can help me?

Thank you.

My react version:
![image](https://user-images.githubusercontent.com/15007654/87945736-89339700-ca77-11ea-9938-2d5d994bce15.png)
![image](https://user-images.githubusercontent.com/15007654/87945741-8e90e180-ca77-11ea-9f81-643d8661ae1d.png)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by fuchien** [comment]
@dboskovic

**Comment by brentkulwicki** [comment]
If you still have questions around this, please don't hesitate to let us know.

**Comment by leognmotta** [comment]
For some reason, I am using `requestDataFromUser` just like @fuchien is using, when I open the modal with errors array, I can't input any data to fix the errors, just following this code snippet from your docs

```js
const passedInData = {
  source: [
    {
      data: {firstName: "John", email: "john@doe.com", userId: 12345},
      errors: [{key: "userId", message: "userId already exists in database", level: "error"}]
    },
    {
      data: {firstName: "", email: "jane@doe", userId: 54321},
      errors: [
        {key: "firstName", message: "Name cannot be blank", level: "error"},
        {key: "email", message: "Email invalid. Please correct email address", level: "error"}
      ]
    }
  ]
}

const launchFlatfile = () => {
  importer.requestDataFromUser(passedInData)
}
```

and it does not work when the modal opens, it shows the red fields with correct validations, but I can't update any value
