### ISSUE TITLE
Abilitiy to control initialization/mounting process

### ISSUE THREAD

**Issue by ramon-villain** [FlatFilers/Adapter#57]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**

Hi we were wondering if there's a way to control when we display the importer, ask you can see in this video (https://www.loom.com/share/e73fb0deccea4f798d77b16d2624eee2) the mounting process is not ideal in terms of UX, it jumps/flicks quite a bit (I assume because of some async tasks), we were wondering if we can control that so we only display the importer when it's ready and mounted. 

We have been trying to select the `iframe` element and changing it's CSS after the new instance is created, and then later on after `requestDataFromUser` is called we just remove the css properties that we added initially, but as you can imagine that's not the best solution.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by brentkulwicki** [comment]
We've actually added a loader to the front of the process at this point, but we don't recommend/allow (in Terms of Service) for direct access to the CSS as it can cause issues with the way some elements load. 

I believe this has been resolved, but if you are still seeing issue, please bring it to our attention.
