### ISSUE TITLE
Ability to provide custom fonts (other than typekit)

### ISSUE THREAD

**Issue by ramon-villain** [FlatFilers/Adapter#58]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Hey, our primary font-face is Inter UI (https://rsms.me/inter/), even tho is clear from the docs that custom fonts are only supported thru Typekit, I'd like to check if you guys forecast supporting other libraries or even accepting a stylesheet link (https://rsms.me/inter/inter.css). I know that this is not necessarily easy because of potential vulnerabilities and sanitization that you will need to add, but that would be a nice feature for users who have to keep a consistent UI/UX.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by dwbelliston** [comment]
Looks like google fonts landed, but can they be used? 

https://github.com/FlatFilers/Adapter/blob/074eb9ab6bce666b68c2ab0d9be48759e035030e/src/obj.settings.ts#L204

Looks like its still only typekit, or am i missing something?

thanks!

**Comment by brentkulwicki** [comment]
Yup. This feature has arrived. 
Blog: https://flatfile.io/blog/importing-and-using-custom-fonts-in-flatfile-portal
Docs: https://flatfile.io/developers/javascript/options/#integrations

**Comment by dwbelliston** [comment]
does this typescript def need to be updated though? when i try to use googleFont the Integrations interface doesnt have googleFont
