### ISSUE TITLE
Licence key logs to console on load.

### ISSUE THREAD

**Issue by jordanparker-me** [FlatFilers/Adapter#62]
I am getting a licence key logging to console from ```webpack:///./node_modules/@sentry/utils/esm/instrument.js```

The ouput is ``` { key: XXXXXXXXXX } ```. This only appears when my Flatfile React component is mounted. I have also ensured that there are no console.log lines within my react code.

Any ideas as to why this library is triggering this logging?

**Comment by dboskovic** [comment]
It's very possible the application is debug logging this. Is it causing issues?
