### ISSUE TITLE
Callback onSuccess

### ISSUE THREAD

**Issue by pranavbabu** [FlatFilers/Adapter#72]
* **I'm submitting a ...**
- [x] feature request

* **Summary**
Would be nice to have an callback function after user clicks on OK button in success dialog.
This will help to do some extra actions like redirect user or refresh browser.
Also would be nice to have options to handle errors if something failed during network request, there was displayError method, but now it's deprecated.

**Comment by NateFerrero** [comment]
Stay tuned on your first request for a way to respond to the OK click in the success dialog.

For custom handling of network request errors, we allow you to listen for errors by attaching a callback to the importer instance:

```TypeScript
importer.registerNetworkErrorCallback(function(error) {
  console.error('network error', error)
})
```

**Comment by NateFerrero** [comment]
Also, if you need to post-validate the data set, you can show an error and request corrections from the user:

```TypeScript
async function processResults(results) {
          robotImporter.displayLoader('Loading message...')
          const isValid = await someValidation(results)
          if (isValid) {
            handleSuccess(results)
          } else {
            robotImporter
              .requestCorrectionsFromUser('One robot must have the call sign ABCD')
              .then(processResults)
          }
        }
```

(assuming `processResults` was the function processing the importer data from `requestDataFromUser`)
