### ISSUE TITLE
IE 11 Back button alignment is broken 

### ISSUE THREAD

**Issue by xor-chintan** [FlatFilers/Adapter#87]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
When using flatfile react application on IE 11 back button in the bottom is not aligned correctly in left. PFA screenshot. notice the back button in footer. 

also header text is not aligned correctly. PFA 2nd screenshot

![back_button](https://user-images.githubusercontent.com/61581846/107618127-0ffbcb80-6c77-11eb-99fc-8caafe00f43a.png)

![image](https://user-images.githubusercontent.com/61581846/107929476-b578ad00-6f9f-11eb-878b-faaf1a7919c9.png)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by brentkulwicki** [comment]
Thanks for reporting. I put in a bug ticket with our Engineering team for this.

**Comment by xor-chintan** [comment]
![image](https://user-images.githubusercontent.com/61581846/107929339-85310e80-6f9f-11eb-9dd4-143e140d1f15.png)
Import label text is also misaligned on right. PFA screenshot

**Comment by MaksymBlank** [comment]
Stylings for IE11 have been fixed.
