### ISSUE TITLE
Show modifications not displaying previous value when cell data deleted with DELETE key

### ISSUE THREAD

**Issue by xor-chintan** [FlatFilers/Adapter#88]
* **I'm submitting a ...**
[v] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Steps to reproduce :: 
Upload file and on review screen when user delete particular cell with DELETE key on keyboard and click on show modifications table it doesn't show actual cell value. PFA attached video
NOTE: if user delete the cell content with backspaces it works as expected.
Browser: Chrome

https://user-images.githubusercontent.com/61581846/107736930-367a3f00-6d29-11eb-9c64-80c230293881.mp4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by MaksymBlank** [comment]
@xor-chintan Hi! Thank you for reporting this! The issue has been resolved and will be deployed to production in the next few days.

Thank you!
