### ISSUE TITLE
Uploading empty csv with only header row redirects back to upload step again and again

### ISSUE THREAD

**Issue by xor-chintan** [FlatFilers/Adapter#89]
* **I'm submitting a ...**
[ ] bug report
* **Summary**
Steps to reproduce:
1. Launch flatfile interface and upload file or pass stream of data having only header rows and no data.
2. Verify column mappings and continue
3. Observe user redirects back to upload screen

Expected behavior -- user should be taken to next screen with empty table

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by MaksymBlank** [comment]
@xor-chintan thank you for reporting this!

When you upload a file with only one row and you mark it as a header row (by clicking "Yes" on the "Does this row contain column names?"), you will be shown an error message saying that your file needs at least 1 row of data (see the screenshot below)

![image](https://user-images.githubusercontent.com/25963776/109182840-fcf6fa00-7752-11eb-9776-bc5fa3043da3.png)

Could you please send us a video of this bug or perhaps the .csv file you are using?

**Comment by brentkulwicki** [comment]
Closing this issue as we have not heard back on it. Please re-open if you are still having problems.
